### PR TITLE
Fixed attachment logic

### LINKED ISSUE #306: Bugfix: not able to change status when reply includes attachments

### PR DESCRIPTION
**Pull request by EVP1989**
Resolves #306

### CODE REVIEW

**Review by villejuutila — APPROVED** [review]

File: src/components/screens/forms/form-reply-screen.tsx [hunk 1]
```diff
@@ -106,24 +106,23 @@ const ReplyScreen: FC = () => {
     metaform.sections?.forEach(section => {
       section.fields?.forEach(field => {
         if (field.type === MetaformFieldType.Files) {
-          let value = getFieldValue(field.name as string);
-          if (!value) {
-            value = { files: [] };
+          const fileValue = getFieldValue(field.name as string) as FileFieldValue;
+          if (fileValue && fileValue.files) {
```
Comment (villejuutila) [inline src/components/screens/forms/form-reply-screen.tsx:110]: FileFieldValue.files is typed as `export type FileFieldValue = {
  files: FileFieldValueItem[]
}`.
Empty array evaluates to true and therefore this condition evaluates to true even if there are no files. Is that intended? If not, `fileValue.files.length` would be more appropriate.
